# Site settings
# baseurl: http://alecive.github.io/lista-bimba-roncioppi
title: Lista bimba
email: alecive87@gmail.com
# url: https://alecive.github.io/lista-bimba-roncioppi/
description: "Lista bimba per la figlia dei Roncioppiiii"
skills: "Per la figlia dei Roncioppiiii"
meta_author: Alessandro Roncone

# Google webmaster tools
# google_verify: 1fM5KCFImdJuWeo8L_Qo7_-tuItbZ5hoIlGg8g14WkY

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffebf3
  primary-rgb: "172,209,233" #"128,179,255"
  secondary: 6d929b #FD6E8A
  secondary-dark: 6d929b #A2122F


# Social networks usernames (many more available: google-plus,
# flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/alecive

# Build settings
markdown: kramdown
permalink: pretty
